# ========================================
# CONFIGURATION COMMUNE
# ========================================

spring:
  profiles:
    active: dev # Profil actif par défaut
  
  application:
    name: banking-app

  jpa:
    open-in-view: false

  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false

# ========================
# SERVER
# ========================
server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

# ========================
# SPRINGDOC / SWAGGER
# ========================
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    operations-sorter: method
    enabled: true
    custom-css-url: /swagger-dark.css